// <auto-generated />
using System;
using Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AntecedenteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UsuarioRegistroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("antecedente", null, t =>
                        {
                            t.HasCheckConstraint("CK_antecedente_tipo", "\"Tipo\" IN ('personal', 'familiar', 'quirurgico')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.AtencionTratamientoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalleCitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DuracionDias")
                        .HasColumnType("integer");

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Indicaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TratamientoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetalleCitaId");

                    b.HasIndex("TratamientoId");

                    b.ToTable("atencion_tratamiento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CargoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("NivelJerarquico")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("cargo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CitaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstadoCitaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoCitaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCancelacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCitaId");

                    b.HasIndex("TipoCitaId");

                    b.HasIndex("UsuarioCancelacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("PacienteId", "Fecha");

                    b.HasIndex("MedicoId", "Fecha", "HoraInicio");

                    b.ToTable("cita", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CitaHistorialEstadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstadoAnteriorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EstadoNuevoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("EstadoAnteriorId");

                    b.HasIndex("EstadoNuevoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cita_historial_estado", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DetalleCitaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotaAtencion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ResumenConsulta")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CitaId")
                        .IsUnique();

                    b.HasIndex("MedicoId");

                    b.ToTable("detalle_cita", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DetalleDiagnosticoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalleCitaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiagnosticoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DetalleCitaId")
                        .IsUnique()
                        .HasDatabaseName("UX_detalle_diagnostico_principal")
                        .HasFilter("\"Principal\" = TRUE");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("DetalleCitaId", "DiagnosticoId")
                        .IsUnique();

                    b.ToTable("detalle_diagnostico", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DiagnosticoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoCie10")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCie10")
                        .IsUnique();

                    b.ToTable("diagnostico", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EmpleadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaRetiro")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("empleado", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EspecialidadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("especialidad", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EstadoCitaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("estado_cita", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HorarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("RetornoActividades")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("SalidaAlmuerzo")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "Fecha")
                        .IsUnique();

                    b.ToTable("horario", null, t =>
                        {
                            t.HasCheckConstraint("CK_horario_jornada", "\"HoraEntrada\" < \"SalidaAlmuerzo\" AND \"SalidaAlmuerzo\" < \"RetornoActividades\" AND \"RetornoActividades\" < \"HoraSalida\"");
                        });
                });

            modelBuilder.Entity("Domain.Entities.LoginIntentoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MotivoFallo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UsernameIntentado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("login_intento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MedicoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistroProfesional")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.ToTable("medico", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MedicoEspecialidadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EspecialidadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("MedicoId")
                        .IsUnique()
                        .HasDatabaseName("UX_medico_especialidad_principal")
                        .HasFilter("\"Principal\" = TRUE");

                    b.HasIndex("MedicoId", "EspecialidadId")
                        .IsUnique();

                    b.ToTable("medico_especialidad", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PacienteAlergiaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reaccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Severidad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sustancia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("paciente_alergia", null, t =>
                        {
                            t.HasCheckConstraint("CK_paciente_alergia_severidad", "\"Severidad\" IS NULL OR \"Severidad\" IN ('leve', 'moderada', 'severa')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.PacienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PermisoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PersonaDireccionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("UX_persona_direccion_principal")
                        .HasFilter("\"Principal\" = TRUE");

                    b.ToTable("persona_direccion", null, t =>
                        {
                            t.HasCheckConstraint("CK_persona_direccion_tipo", "\"Tipo\" IS NULL OR \"Tipo\" IN ('residencia', 'trabajo')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.PersonaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SexoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SexoId");

                    b.HasIndex("TipoDocumentoId", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PersonaTelefonoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("UX_persona_telefono_principal")
                        .HasFilter("\"Principal\" = TRUE");

                    b.ToTable("persona_telefono", null, t =>
                        {
                            t.HasCheckConstraint("CK_persona_telefono_tipo", "\"Tipo\" IS NULL OR \"Tipo\" IN ('movil', 'fijo', 'trabajo')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RolPermisoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId", "PermisoId")
                        .IsUnique();

                    b.ToTable("rol_permiso", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SesionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dispositivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EmitidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotivoRevocacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("RefreshExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "RevocadoEn");

                    b.ToTable("sesion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SexoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("sexo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoCitaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipo_cita", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoDocumentoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TokenRecuperacionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpSolicitud")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UsadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("token_recuperacion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TratamientoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tratamiento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TratamientoPosologiaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dosis")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DuracionDias")
                        .HasColumnType("integer");

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Indicaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TratamientoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId")
                        .IsUnique();

                    b.ToTable("tratamiento_posologia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AntecedenteEntity", b =>
                {
                    b.HasOne("Domain.Entities.PacienteEntity", "Paciente")
                        .WithMany("Antecedentes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.UsuarioEntity", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Paciente");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("Domain.Entities.AtencionTratamientoEntity", b =>
                {
                    b.HasOne("Domain.Entities.DetalleCitaEntity", "DetalleCita")
                        .WithMany("AtencionesTratamiento")
                        .HasForeignKey("DetalleCitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TratamientoEntity", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleCita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("Domain.Entities.CitaEntity", b =>
                {
                    b.HasOne("Domain.Entities.EstadoCitaEntity", "EstadoCita")
                        .WithMany()
                        .HasForeignKey("EstadoCitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MedicoEntity", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PacienteEntity", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoCitaEntity", "TipoCita")
                        .WithMany()
                        .HasForeignKey("TipoCitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.UsuarioEntity", "UsuarioCancelacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCancelacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.UsuarioEntity", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoCita");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("TipoCita");

                    b.Navigation("UsuarioCancelacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Domain.Entities.CitaHistorialEstadoEntity", b =>
                {
                    b.HasOne("Domain.Entities.CitaEntity", "Cita")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EstadoCitaEntity", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EstadoCitaEntity", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cita");

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.DetalleCitaEntity", b =>
                {
                    b.HasOne("Domain.Entities.CitaEntity", "Cita")
                        .WithOne("DetalleCita")
                        .HasForeignKey("Domain.Entities.DetalleCitaEntity", "CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MedicoEntity", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Domain.Entities.DetalleDiagnosticoEntity", b =>
                {
                    b.HasOne("Domain.Entities.DetalleCitaEntity", "DetalleCita")
                        .WithMany("DetallesDiagnostico")
                        .HasForeignKey("DetalleCitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DiagnosticoEntity", "Diagnostico")
                        .WithMany()
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleCita");

                    b.Navigation("Diagnostico");
                });

            modelBuilder.Entity("Domain.Entities.EmpleadoEntity", b =>
                {
                    b.HasOne("Domain.Entities.CargoEntity", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PersonaEntity", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.HorarioEntity", b =>
                {
                    b.HasOne("Domain.Entities.MedicoEntity", "Medico")
                        .WithMany("Horarios")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Domain.Entities.LoginIntentoEntity", b =>
                {
                    b.HasOne("Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.MedicoEntity", b =>
                {
                    b.HasOne("Domain.Entities.EmpleadoEntity", "Empleado")
                        .WithOne("Medico")
                        .HasForeignKey("Domain.Entities.MedicoEntity", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Domain.Entities.MedicoEspecialidadEntity", b =>
                {
                    b.HasOne("Domain.Entities.EspecialidadEntity", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.MedicoEntity", "Medico")
                        .WithMany("Especialidades")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("Domain.Entities.PacienteAlergiaEntity", b =>
                {
                    b.HasOne("Domain.Entities.PacienteEntity", "Paciente")
                        .WithMany("Alergias")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Entities.PacienteEntity", b =>
                {
                    b.HasOne("Domain.Entities.PersonaEntity", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.PersonaDireccionEntity", b =>
                {
                    b.HasOne("Domain.Entities.PersonaEntity", "Persona")
                        .WithMany("Direcciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.PersonaEntity", b =>
                {
                    b.HasOne("Domain.Entities.SexoEntity", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.TipoDocumentoEntity", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sexo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Domain.Entities.PersonaTelefonoEntity", b =>
                {
                    b.HasOne("Domain.Entities.PersonaEntity", "Persona")
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.RolPermisoEntity", b =>
                {
                    b.HasOne("Domain.Entities.PermisoEntity", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RolEntity", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Domain.Entities.SesionEntity", b =>
                {
                    b.HasOne("Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.TokenRecuperacionEntity", b =>
                {
                    b.HasOne("Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.TratamientoPosologiaEntity", b =>
                {
                    b.HasOne("Domain.Entities.TratamientoEntity", "Tratamiento")
                        .WithOne("Posologia")
                        .HasForeignKey("Domain.Entities.TratamientoPosologiaEntity", "TratamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("Domain.Entities.UsuarioEntity", b =>
                {
                    b.HasOne("Domain.Entities.EmpleadoEntity", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("Domain.Entities.UsuarioEntity", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.RolEntity", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Domain.Entities.CitaEntity", b =>
                {
                    b.Navigation("DetalleCita");

                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("Domain.Entities.DetalleCitaEntity", b =>
                {
                    b.Navigation("AtencionesTratamiento");

                    b.Navigation("DetallesDiagnostico");
                });

            modelBuilder.Entity("Domain.Entities.EmpleadoEntity", b =>
                {
                    b.Navigation("Medico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.MedicoEntity", b =>
                {
                    b.Navigation("Especialidades");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Domain.Entities.PacienteEntity", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("Antecedentes");
                });

            modelBuilder.Entity("Domain.Entities.PermisoEntity", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Domain.Entities.PersonaEntity", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("Domain.Entities.RolEntity", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Domain.Entities.TratamientoEntity", b =>
                {
                    b.Navigation("Posologia");
                });

            modelBuilder.Entity("Domain.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
